---
- name: Install Applications
  hosts: all
  become: true

  tasks:
    - name: Install Standard App's
      ansible.builtin.apt:
        name:
          - neofetch
          - docker.io
          - docker-compose
          - glances
          - cockpit
          - cockpit-pcp
          - cockpit-machines
        state: present
        update_cache: true
