---
- name: Check disk space
  hosts: all

  tasks:
    - name: Capture disk usage
      command: df -Ph /dev/sda /dev/sdb2 /dev/sdc /dev/mmcblk0p2
      register: disk_usage

    - name: Send disk usage to Discord
      community.general.discord:
        webhook_id: "webhook_ID"
        webhook_token: "webhook_token"
        content:  |
          # Disk Usage Summary:
          ```
          {{ disk_usage.stdout | regex_replace('(\\s+)', ' | ') }}
          ```
