---
- name: Check disk space
  hosts: all

  tasks:
    - name: Check disk space available
      ansible.builtin.shell:
        cmd: |
          df -Ph /dev/sda /dev/sdb2 /dev/sdc /dev/mmcblk0p2
#          df -Ph / | awk 'NR==2 {print $5}'
        executable: /bin/bash
      changed_when: false
      check_mode: false
      register: disk_usage

    - name: Send an embedded message to the Discord channel
      community.general.discord:
        webhook_url: https://discord.com/api/webhooks/1225440016575103077/N56PO8X6Jf3mTkSWDKhelqpdw8mklCcMmUEmWQZxO9uiHuxIQE68pN0Gfoecjbt-1xMJ
        embeds:
          - title: "Embedded message"
            description: "Disk Space Usage"
            footer:
              text: "Ironpi"
            image:
              url: "https://your_image_url.png"
