---
- name: Check disk space
  hosts: all

  tasks:
    - name: Capture disk usage
      command: df -Ph /dev/sda /dev/sdb2 /dev/sdc /dev/mmcblk0p2
      register: disk_usage

    - name: Send disk usage to Discord
      community.general.discord:
        webhook_id: "225440016575103077"
        webhook_token: "N56PO8X6Jf3mTkSWDKhelqpdw8mklCcMmUEmWQZxO9uiHuxIQE68pN0Gfoecjbt-1xMJ"
        content: "{{ disk_usage.stdout }}"
