---
- name: Check disk space
  hosts: all

  tasks:
    - name: Check disk space available
      ansible.builtin.shell:
        cmd: |
          set -euo pipefail
          df -Ph /dev/sda /dev/sdb2 /dev/sdc /dev/mmcblk0p2
#          df -Ph / | awk 'NR==2 {print $5}'
        executable: /bin/bash
      changed_when: false
      check_mode: false
      register: disk_usage

    - name: Send discord message with disk space output
      uri:
        url: https://discord.com/api/webhooks/your_webhook_id
        method: POST
        body_format: json
        body: |
          {
            "content": "```{{ disk_usage.stdout }}```"
          }
        headers:
          Content-Type: application/json
        status_code: 200
     # when: disk_usage.stdout[:-1]|int > 80
